language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
  - composer self-update
  - composer install --dev
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p Tests/